//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
	public class Cube
	{
		private GameObject _gameObject;
		public string CubeName { get; private set; }

		public Cube(int x, int y, float startx, float starty, float cubeSize, float cubeStratch, string cubeName)
		{
			CubeName = cubeName;

			_gameObject = (GameObject)GameObject.Instantiate (GameObject.Find (cubeName).gameObject);
			_gameObject.transform.position = 
				new Vector3 (startx + cubeSize * cubeStratch * (x + 0.5f), cubeSize / 2.0f, starty + cubeSize * (y + 0.5f));
			_gameObject.transform.localScale = new Vector3 (cubeSize*cubeStratch, cubeSize, cubeSize);
		}
	}
}

