//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace AssemblyCSharp
{
	public class FieldManager
	{
		private Cube[,] _cubes;
		private int _width;
		private int _height;

		public FieldManager (int width, int height, float x, float y, float cubeSize = 1.0f, float cubeStratch = 1.0f)
		{ 
			_width = width;
			_height = height;
			_cubes = new Cube[width, height];

			for (int i = 0; i < width; i++) 			
				for (int j = 0; j < height; j++) 
					_cubes[i, j] = new Cube(i, j, x, y, cubeSize, cubeStratch, GetCubeName(i, j));			
		}

		private string GetCubeName(int x, int y)
		{
			bool haveSilverNeighbor = false;
			for (int i = x - 1; i < x + 1; i++) 
			{
				for (int j = y - 1; j < y + 1; j++)
				{
					if ((i == x && j == y) || i < 0 || j < 0 || i == _width || j == _height) continue;
					if (_cubes[i, j] != null)
					{
						if (_cubes[i, j].CubeName == "SilverCube")
						{
							haveSilverNeighbor = true;
							break;
						}
					}

				}
			}

			float randValue = UnityEngine.Random.Range (0, 1.0f);
			UnityEngine.Debug.Log (randValue);

			if (haveSilverNeighbor) 
			{
				return randValue > 1.0f/3.0f ? 
					(randValue > 2.0f/3.0f ? "OrangeCube" : "GreenCube") : "RedCube";
			} else 
			{
				return randValue > 1.0f/4.0f ? 
						(randValue > 2.0f/4.0f ? 
					 		(randValue > 3.0f/4.0f ? 
					 "OrangeCube" : 
					 	"GreenCube") : 
					 		"RedCube") : 
								"SilverCube";
			}
		}
	}
}

